name: Generate Profile Assets

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Generate Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: AnhadMahajan
          # The output file is written to the output branch by default
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. Fetch Latest Blog Posts from Medium
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Your Medium feed URL
          feed_list: "https://medium.com/feed/@anhadmahajan06"
